name: Auto Merge dev to master

on:
  push:
    branches:
      - dev

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge dev into master
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Fetch all branches
          git fetch origin master

          # Checkout master
          git checkout master

          # Merge dev into master
          git merge origin/dev -m "Auto-merge dev into master"

          # Push changes to master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
