name: Auto PR from dev to master

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request from dev to master
        uses: peter-evans/pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: dev
          target: master
          title: "Sync: dev → master"
          body: |
            This PR was automatically created to sync changes from `dev` into `master`.
          draft: false
